repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [ "--branch", "main", "--branch", "develop" ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.0
    hooks:
      - id: jupytext
        args: [ --from, ipynb, --to, "py" ]